spring:
  application:
    name: openvalidation-ide-backend
  profiles:
    active: local
  datasource:
    platform: h2
    url: jdbc:h2:mem:openvalidation_ide;MODE=MYSQL
    initialization-mode: always
  # Hibernate ddl auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
springdoc:
  version: '@org.springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    displayRequestDuration: true
    tagsSorter: alpha

cors-headers: ${CORS_HEADERS:#{"null"}}