spring:
  application:
    name: openvalidation-ide-backend
  profiles:
    active: local
  # Hibernate ddl auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
springdoc:
  version: '@org.springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    displayRequestDuration: true
    tagsSorter: alpha